# Add this file to your home directory to use it
# for automated login to bugzilla
# 
---
:bugzilla_options:
  :bugzilla_uri: https://bugzilla.redhat.com/
  :debug: true
:bugzilla_credentials:
  :username: Login Name
  :password: Password
