# Add this file to your home directory to use it
# for automated login to bugzilla
# 
---
:bugzilla_options:
  :bugzilla_uri: https://bugzilla.redhat.com/xmlrpc.cgi
  :debug: True
:bugzilla_credentials:
  :username: Login Name
  :password: Password
