common: &common
  bugzilla:
    uri:      https://bugzilla.redhat.com/
    product:  "CloudForms Management Engine"
    username: calvin
    password: hobbes

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common

