common: &common
  bugzilla:
    uri:               "https://bugzilla.redhat.com/"
    show_bug_prefix:   "/show_bug.cgi?id="
    product:           "CloudForms Management Engine"
    username:          "calvin"
    password:          "hobbes"
    timeout:           180
    max_clients:       1
    issues_per_client: 100
    update_interval:   3600

  sidekiq:
    queue:       "cfme_bz"

  cfme_git:
    repo_path: "/Users/calvin/projects/cfme/"
    releases:
      cfme-5.2.z:
        - "production/5.2.2.x"
        - "upstream/master"
      cfme-5.3:
        - "production/5.3.0.x"
        - "upstream/master"

development:
  <<: *common

test:
  <<: *common
  bugzilla:
    uri:               "https://partner-bugzilla.redhat.com"

production:
  <<: *common

