dashboard:
  filters:
  - name: All Bugs
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND flags NOT LIKE '%cfme-future%'"
  - name: All RFEs
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND keywords = 'FutureFeature' AND flags LIKE '%cfme-future%'"
  - name: All DOCs
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component = 'Documentation'"
  - name: Blocker Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags LIKE '%blocker=%'"
  - name: Urgent Severity Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND severity = 'urgent'"
  - name: High Severity Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND severity = 'high'"
  - name: Medium Severity Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND severity = 'medium'"
  - name: Low Severity Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND severity = 'low'"
  - name: "Created Last 7 Days"
    sqlfilter: "component != 'Documentation' AND created_on >= (current_date - 7)"
  - name: "Modified Last 7 Days"
    sqlfilter: "component != 'Documentation' AND updated_on >= (current_date - 7)"
  - name: "On QA Last 7 Days"
    sqlfilter: "component != 'Documentation' AND updated_on >= (current_date - 7) AND status = 'ON_QA'"
  - name: "Bug Age 0-30 Days"
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND created_on >= (current_date - 30)"
  - name: "Bug Age 31-60 Days"
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND created_on >= (current_date - 60) AND created_on < (current_date - 30)"
  - name: "Bug Age 61-90 Days"
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND created_on >= (current_date - 90) AND created_on < (current_date - 60)"
  - name: "Bug Age 91-180 Days"
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND created_on >= (current_date - 180) AND created_on < (current_date - 90)"
  - name: "Bug Age 181-270 Days"
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND created_on >= (current_date - 270) AND created_on < (current_date - 180)"
  - name: "Bug Age 271-360 Days"
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND created_on >= (current_date - 360) AND created_on < (current_date - 270)"
  - name: "Bug Age 361-1000 Days"
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND created_on >= (current_date - 1000) AND created_on < (current_date - 360)"
  - name: "5.2.z Open Proposed"
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND flags LIKE '%cfme-5.2.z=%'"
  - name: "5.2.z On QA"
    sqlfilter: "status = 'ON_QA' AND classification = 'Red Hat' AND flags LIKE '%cfme-5.2.z=+%'"
  - name: "5.2.z Post Modified"
    sqlfilter: "(status = 'POST' OR status = 'MODIFIED') AND classification = 'Red Hat' AND flags LIKE '%cfme-5.2.z=%'"
  - name: "5.3 Post Modified"
    sqlfilter: "(status = 'POST' OR status = 'MODIFIED') AND classification = 'Red Hat' AND flags LIKE '%cfme-5.3=%'"
