dashboard:
  filters:
  - name: All Bugs
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component != 'Documentation' AND flags NOT LIKE '%cfme-future%'"
  - name: All RFEs
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND keywords = 'FutureFeature' AND flags LIKE '%cfme-future%'"
  - name: All DOCs
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND component = 'Documentation'"
  - name: Urgent Severity Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND severity = 'urgent'"
  - name: High Severity Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND severity = 'high'"
  - name: Medium Severity Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND severity = 'medium'"
  - name: Low Severity Issues
    sqlfilter: "(status = 'NEW' OR status = 'ASSIGNED' OR status = 'ON_DEV') AND classification = 'Red Hat' AND component != 'Documentation' AND keywords NOT LIKE '%FutureFeature%' AND flags NOT LIKE '%cfme-future%' AND severity = 'low'"
